
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 731186774328-9fp8lhqr0gd3frk0qj07tn0u62ta4ls1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
server:
  port: 8081
jwt:
  issuer: myDomainName.com
  secret_key: key-is-secret